
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: operator
rules:
- apiGroups:
  - crd.demo.com
  resources:
  - podtatoheads
  - podtatoheads/finalizers
  - podtatoheads/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - crd.demo.com
  resources:
  - leases
  verbs:
  - get
  - patch
  - update
  - list
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - patch
  - update
  - create
  - delete
- apiGroups: ["", "apps"]
  resources: ["statefulsets", "events", "serviceaccounts", "deployments", "configmaps", "services", "secrets", "persistentvolumeclaims", "pods", "pods/log"]
  verbs: ["get", "watch", "list", "create", "delete", "update"]