apiVersion: crd.demo.com/v1alpha1
kind: PodTatoHead
metadata:
  name: podtatohead
  namespace: operator
spec:
  replicaCount: 1
  name: pod-tato-head
  namespace: operator
  version: v0.1.1
  main:
    image: kaleoum/podtato-main:v0.1.1
    name: main
    port: 9000

  hats:
    image: kaleoum/podtato-hats:v0.1.1
    name: hats
    port: 9001

  leftLeg:
    image: kaleoum/podtato-left-leg:v0.1.1
    name: left-leg
    port: 9002

  leftArm:
    image: kaleoum/podtato-left-arm:v0.1.1
    name: left-arm
    port: 9003

  rightLeg:
    image: kaleoum/podtato-right-leg:v0.1.1
    name: right-leg
    port: 9004

  rightArm:
    image: kaleoum/podtato-right-arm:v0.1.1
    name: right-arm
    port: 9005
